<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{{include file='layouts/title.tpl'}} 
<link href="{{$smarty.const.WEBSITE_URL}}public/style/reset.css" type="text/css" rel="stylesheet" />
<link href="{{$smarty.const.WEBSITE_URL}}public/style/style.css" type="text/css" rel="stylesheet" /> 
<link href="{{$smarty.const.WEBSITE_URL}}public/style/validationEngine.jquery.css" type="text/css" rel="stylesheet" /> 
<link href="{{$smarty.const.WEBSITE_URL}}public/style/func.css" type="text/css" rel="stylesheet" /> 
<link rel="stylesheet" href="{{$smarty.const.WEBSITE_URL}}/public/assets/css/jquery-ui.css" />
<link rel="stylesheet" href="{{$smarty.const.WEBSITE_URL}}/public/assets/css/jquery.ui.datepicker.css" />
<script src="{{$smarty.const.WEBSITE_URL}}public/js/jquery-1.10.1.min.js" type="text/javascript"></script> 
<script src="{{$smarty.const.WEBSITE_URL}}/public/assets/js/jquery-ui.js"></script>
<script src="{{$smarty.const.WEBSITE_URL}}/public/assets/js/jquery.ui.datepicker.js"></script>
<script src="{{$smarty.const.WEBSITE_URL}}/public/js/searchform.js"></script>
 
</head>

<body>
{{include file='layouts/headerandsearch.tpl'}} 
<div class="mian">
    <div class="content">
    	<div class="article">
        <h5>Términos y Condiciones</h5>
            <p>
            	Tu email es privado y BUSCATICKETS no tiene acceso a el.BUSCATICKETS solo usara tu email para enviarte eventos,alertas y notificaciones con tu consentimiento. Usted puede cancelar todas estas notificaciones en su perfil o bien poniéndose en contacto con nosotros. 
            </p>
            <p>
            	BUSCATICKETS no quiere que te pierdas ningun evento, su intención es darte información sobre los artistas para que puedas compartir buenos momentos con otros usuarios. No se permitira el uso inapropiado del sitio web. - Para cualquier otra pregunta, recuerde que siempre puede ponerse en contacto con nosotros.
            </p>  
            <p>
            	<b>Términos y Condiciones</b>El acceso y uso del servicio en buscatickets.com implica que usted acepta las siguientes condiciones.
            </p>
            <p>
            	<b>Información Legal</b> Afiliados Publiweb S.L. es dueña de la página web buscatickets.com, ubicada en Bilbao, España. Las Arenas, Código Postal 48930 Provided C.I.F. B95609947,registrado en el Registro Mercantil de Vizcaya, 1er registro (De aquí en adelante "BUSCATICKETS"). Las presentes condiciones regulan el acceso y uso del servicio de la web BUSCATICKETS, que BUSCATICKETS pone al alcance de los usuarios interesados en sus servicios y contenidos. BUSCATICKETS puede cambiar en cualquier momento, sin aviso previo, el diseño, presentación y/o de la configuración de la web para alguno o todos sus servicios. El uso de esta web implica la total aceptación de las condiciones publicadas por BUSCATICKETS. Igualmente, BUSCATICKETS notifica al usuario de esta web que estas condiciones pueden ser modificadas sin previo aviso. Por lo tanto,el Usuario debe leer atentamente las presentes Condiciones cada vez que proceda a utilizar el servicio, ya que las condiciones pueden haber sufrido cambios.La utilización de ciertos servicios ofrecidos a los Usuarios a través del Sitio Web pueden estar sujetos a sus propias condiciones que, al ser usadas, prevén la sustitución, modificación y/o finalización de las presentes Condiciones Generales de Uso. Por lo tanto, antes de utilizar dichos servicios, el Usuario también debe leer atentamente y aceptar las condiciones  correspondientes.   <p>
            	<b>Exclusión de Responsabilidad y Garantías</b> buscatickets.com no es responsable del contenido que aparece en las páginas web del dominio buscatickets.com. Esta información es proporcionada por terceros y puede contener errores e imprecisiones. buscatickets.com siempre recomienda la comparación de la información con la institución que organiza los diferentes eventos publicados. buscatickets.com no se hace responsable por los daños y perjuicios causados ​​por cualquier tipo de información errónea proporcionada aquí. buscatickets.com no ofrece ninguna garantía para el correcto funcionamiento de los servicios que ofrece a sus usuarios.
            </p>
            <p>
            	<b>Registro de Usuarios y acceso</b> buscatickets.com basa el uso de sus servicios condicionado a la previa cumplimentación del correspondiente registro de Usuario , la selección de un identificador ( dirección de correo electrónico del usuario ) y la contraseña, que el Usuario se compromete a mantener y utilizar con la debida diligencia . El uso de la contraseña es personal e intransferible, no se permite que usted asigne la contraseña, ni siquiera temporal , a terceros. En este sentido, el Usuario deberá adoptar las medidas necesarias en la custodia de la contraseña seleccionada, evitando el uso de la contraseña por terceros. En consecuencia, el Usuario es el único responsable del uso que pueda hacerse de la contraseña, con completa indemnización para BUSCATICKETS. El registro citado se maneja como se indica expresamente en el propio servicio o en las Condiciones Particulares que, en su caso, las regulan. Toda la información que facilite el Usuario a través del servicio deberá ser veraz. A estos efectos, el Usuario garantiza la autenticidad de todos aquellos datos que comunique como consecuencia de la cumplimentación de los formularios necesarios para la suscripción de los Servicios. Del mismo modo, es responsabilidad del Usuario mantener toda la información facilitada a BUSCATICKETS actualiza constantemente para que se corresponda en todo momento a la situación real del Usuario. En cualquier caso, el Usuario será el único responsable de las declaraciones falsas o inexactas que realice y de los perjuicios que cause a BUSCATICKETS o terceros a través de la información proporcionada.
           </p>
		   <p>
            	<b>Condiciones de Acceso y Uso de la Página Web</b> El usuario se compromete a hacer un uso consciente de la Web y de los servicios accesibles a través de ella , estando completamente sujeta a la Ley, la moral, y las condiciones específicas aplicables, a fin de mantener el debido respeto a los demás usuarios. Cualquier uso distinto del propósito de este sitio web está expresamente prohibido. En este sentido, el Usuario deberá renunciar al uso de cualquiera de los materiales y el contenido informativo de esta página web, con fines o efectos ilícitos, prohibidos expresamente en las presentes Condiciones Generales de Uso, así como de las condiciones específicas que pueden ser impuestas, que son contrarias a los derechos e intereses de BUSCATICKETS , sus miembros y/o terceros. El Usuario responderá a lo anterior en el caso de una violación o incumplimiento de las obligaciones y/o que , de cualquier modo (incluida la introducción o difusión de virus ), daños, inhabilitaciones, sobrecargas, dificulte o impida la función normal de los materiales y el contenido informativo del sitio Web, la información y los documentos , archivos y toda clase de contenidos alojados en cualquier equipo tecnológico perteneciente a BUSCATICKETS, sus miembros o de cualquier otro usuario del Sitio Web. De conformidad con la política antiSPAM de BUSCATICKETS, el Usuario es obligado a llevar a cabo acciones con fines promocionales o publicitarios , así como el envío de comunicaciones comerciales de cualquier tipo y a través de cualquier medio de comunicación que no se solicitan o previamente aprobados por BUSCATICKETS y/o partes interesadas. El Usuario que intencionalmente o culpablemente no cumpla con cualquiera de las anteriores obligaciones será responsable de todos los daños causados ​​.
            </p>
			<p>
            	<b>Obligaciones para el uso de BUSCATICKETS<br />Obligaciones generales para el uso de BUSCATICKETS</b> 
Los datos requeridos para el registro del usuario, así como para el resto de los servicios debe ser veraz. La información proporcionada por el Usuario debe ser legalmente válida y cumplir con los requisitos y condiciones de BUSCATICKETS. Quedan prohibidas las actividades que se sospeche como ilegales de acuerdo con la ley nacional, autonómica o internacional, o que se sospecha que es ilegal o en conflicto con los principios de buena fe, que contienen información presuntamente penal, como la calumnia, amenazas, insultos o cualesquiera otros delitos enunciados en el código penal, que no entran dentro de los parámetros de calidad establecidos por Buscatickets.            </p>
             <p>
            	<b>Política de aprobación de perfiles</b>La Política para aprobar perfiles está diseñada para regular el contenido de los perfiles con el fin de asegurar un ambiente general de la calidad del contenido, del lenguaje y de las intenciones apropiadas para la seguridad de todos sus usuarios. No serán aprobados perfiles que contengan: * Información de contacto personal , como números de teléfono * Contenido sexualmente explícito o lenguaje sexualmente sugestivo * difamatorio , abusivo, agresivo o violento * sugerencia sexual o desnudez en la foto de BUSCATICKETS , a su discreción, se reserva el derecho de rechazar a los usuarios si la información publicada no demuestra, en opinión de BUSCATICKETS, un nivel de confianza,de seguridad y de credibilidad suficiente para su inclusión en la comunidad de BUSCATICKETS de usuarios. En este sentido, BUSCATICKETS se reserva el derecho de eliminar sin previo aviso a los usuarios registrados que no cumplan con los principios de BUSCATICKETS de calidad y veracidad. Teniendo en cuenta que es imposible para BUSCATICKETS controlar todo el contenido publicado, no asume responsabilidad alguna por ello. Cualquier usuario que haya facilitado la información o realizado acciones que entren en conflicto con la ley activa asume la responsabilidad exclusiva de los perjuicios y consecuencias sufridas, eximiendo de cualquier responsabilidad a BUSCATICKETS. En cualquier caso, exhaustivos controles se utilizan periódicamente para asegurarse de que los perfiles cumplen con la política y que la calidad de los contenidos publicados se mantiene. Con la ayuda de todos, podemos hacer de BUSCATICKETS un sitio mejor, así que si encuentras contenido inapropiado, por favor ponte en contacto nosotros en webmaster@buscatickets.com. Los usuarios que violen cualquiera de las condiciones aquí mencionadas serán eliminados del sitio web.  </p>
            <p>
            	<b>Enlaces a Sitios de Terceros</b> El Sitio contiene enlaces a otras páginas web que no son controladas por BUSCATICKETS. Muchos de estos servicios o de los sitios externos pueden formar parte de los sitios web afiliados de una manera u otra con BUSCATICKETS. La función de los links es exclusivamente la de informar al usuario y no implica el apoyo o respaldo por parte de BUSCATICKETS de la página web o de su contenido. El usuario que decide utilizar cualquiera de los enlaces para acceder a las páginas web de terceros, deja el sitio y  asume la responsabilidad de cualquier riesgo que puediera derivarse por la página web visitada. </p>  
            <p>
            	<b>Legislación aplicable y jurisdicción</b> Las presentes condiciones generales y el resto de condiciones legales del sitio web se regirán por la ley española. Cualquier duda que pueda surgir o derivarse de las acciones que el usuario del servicio de buscatickets.com y sus servicios y contenidos y sobre la interpretación, aplicación, cumplimiento o incumplimiento de lo aquí establecido, buscatickets.com y el Usuario, con renuncia expresa a cualquier otra legislación que pudiera corresponderles, se someten a la jurisdicción de los Juzgados y Tribunales de Bilbao.  </p>
        </div>
    </div>
	<div class="h-blackbg"></div>
</div>
{{include file='layouts/footer.tpl'}}  